const mongoose = require('mongoose')
const University = require('./models/University')
const { mongoDBURL } = require('./config/config')

const universities = [
  {
    flag: "🇳🇬",
    name: "Nile University of Nigeria",
    country: "Nigeria",
    programs: ["Software Engineering", "Computer Science", "Law"],
    minGPA: 3.5,
    deadline: "Oct 15",
    language: "English",
    match: 95,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇳🇬",
    name: "Baze University",
    country: "Nigeria",
    programs: ["Computing", "Information Technology", "Business"],
    minGPA: 3.3,
    deadline: "Jan 19",
    language: "English",
    match: 92,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇩🇪",
    name: "TU Munich",
    country: "Germany",
    programs: ["Engineering", "Computer Science"],
    minGPA: 3.2,
    deadline: "Nov 30",
    language: "English",
    match: 93,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇸🇪",
    name: "KTH Royal Institute",
    country: "Sweden",
    programs: ["Technology", "Engineering"],
    minGPA: 3.0,
    deadline: "Jan 15",
    language: "English",
    match: 88,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇧🇪",
    name: "KU Leuven",
    country: "Belgium",
    programs: ["All programs"],
    minGPA: 3.0,
    deadline: "Feb 1",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇳🇱",
    name: "University of Amsterdam",
    country: "Netherlands",
    programs: ["Data Science", "Business"],
    minGPA: 3.1,
    deadline: "Feb 15",
    language: "English",
    match: 82,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇨🇦",
    name: "University of Toronto",
    country: "Canada",
    programs: ["All programs"],
    minGPA: 3.3,
    deadline: "Feb 1",
    language: "English",
    match: 81,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇬🇧",
    name: "University of Southampton",
    country: "United Kingdom",
    programs: ["Computer Science", "Engineering", "Data Science"],
    minGPA: 3.4,
    deadline: "Mar 15",
    language: "English",
    match: 90,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇹🇷",
    name: "Ostim Technical University",
    country: "Turkey",
    programs: ["Computing", "Software Engineering", "Mechanical Engineering"],
    minGPA: 3.0,
    deadline: "Jan 19",
    language: "English",
    match: 89,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇮🇹",
    name: "Roma Tre University",
    country: "Italy",
    programs: ["Law", "Political Science", "International Relations"],
    minGPA: 3.2,
    deadline: "Apr 30",
    language: "English",
    match: 87,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇨🇿",
    name: "University of Hradec Kralove",
    country: "Czech Republic",
    programs: ["Political Science", "Information Technology"],
    minGPA: 3.0,
    deadline: "May 15",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇺🇸",
    name: "MIT",
    country: "United States",
    programs: ["Computer Science", "Artificial Intelligence"],
    minGPA: 3.8,
    deadline: "Jan 1",
    language: "English",
    match: 96,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "Stanford University",
    country: "United States",
    programs: ["Software Systems", "Entrepreneurship"],
    minGPA: 3.7,
    deadline: "Jan 5",
    language: "English",
    match: 94,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "University of Michigan",
    country: "United States",
    programs: ["Engineering", "Applied Science"],
    minGPA: 3.2,
    deadline: "Dec 15",
    language: "English",
    match: 88,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇬🇧",
    name: "University of Oxford",
    country: "United Kingdom",
    programs: ["All programs", "Mathematics"],
    minGPA: 3.9,
    deadline: "Oct 15",
    language: "English",
    match: 91,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇬🇧",
    name: "University of Cambridge",
    country: "United Kingdom",
    programs: ["Computer Science", "Technology"],
    minGPA: 3.9,
    deadline: "Oct 15",
    language: "English",
    match: 90,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇬🇧",
    name: "Glasgow Caledonian University",
    country: "United Kingdom",
    programs: ["Business Administration", "Engineering"],
    minGPA: 3.0,
    deadline: "Feb 28",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇫🇷",
    name: "University of Clermont",
    country: "France",
    programs: ["Biotechnology", "Business"],
    minGPA: 3.1,
    deadline: "Mar 1",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇱🇻",
    name: "Riga Technical University",
    country: "Latvia",
    programs: ["Computer Science", "Information Technologies"],
    minGPA: 2.8,
    deadline: "May 30",
    language: "English",
    match: 83,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇦🇹",
    name: "UAS Upper Austria",
    country: "Austria",
    programs: ["Engineering", "Information Technologies"],
    minGPA: 3.0,
    deadline: "Apr 15",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇸🇬",
    name: "National University of Singapore",
    country: "Singapore",
    programs: ["Data Science", "Computer Science"],
    minGPA: 3.5,
    deadline: "Feb 20",
    language: "English",
    match: 92,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇸🇬",
    name: "Nanyang Technological University",
    country: "Singapore",
    programs: ["Engineering", "Technology"],
    minGPA: 3.4,
    deadline: "Mar 1",
    language: "English",
    match: 89,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇯🇵",
    name: "University of Tokyo",
    country: "Japan",
    programs: ["Technology", "All programs"],
    minGPA: 3.5,
    deadline: "Dec 20",
    language: "English",
    match: 87,
    type: "Study Abroad",
    region: "asia",
  },
  {
    flag: "🇯🇵",
    name: "Kyoto University",
    country: "Japan",
    programs: ["Engineering", "Biotechnology"],
    minGPA: 3.3,
    deadline: "Jan 10",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇨🇭",
    name: "ETH Zurich",
    country: "Switzerland",
    programs: ["Computer Science", "Engineering"],
    minGPA: 3.6,
    deadline: "Nov 15",
    language: "English",
    match: 93,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇨🇭",
    name: "EPFL",
    country: "Switzerland",
    programs: ["Data Science", "Technology"],
    minGPA: 3.5,
    deadline: "Dec 1",
    language: "English",
    match: 89,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇦🇺",
    name: "University of Melbourne",
    country: "Australia",
    programs: ["All programs", "Business"],
    minGPA: 3.2,
    deadline: "Mar 31",
    language: "English",
    match: 86,
    type: "Study Abroad",
    region: "asia",
  },
  {
    flag: "🇦🇺",
    name: "Australian National University",
    country: "Australia",
    programs: ["Information Technology", "Engineering"],
    minGPA: 3.3,
    deadline: "Apr 15",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇨🇦",
    name: "McGill University",
    country: "Canada",
    programs: ["Software Engineering", "Law"],
    minGPA: 3.4,
    deadline: "Jan 15",
    language: "English",
    match: 88,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇨🇦",
    name: "University of British Columbia",
    country: "Canada",
    programs: ["Computer Science", "Applied Science"],
    minGPA: 3.2,
    deadline: "Jan 30",
    language: "English",
    match: 87,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇳🇱",
    name: "TU Delft",
    country: "Netherlands",
    programs: ["Engineering", "Technology"],
    minGPA: 3.3,
    deadline: "Jan 15",
    language: "English",
    match: 91,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇳🇱",
    name: "Eindhoven University of Tech",
    country: "Netherlands",
    programs: ["Computer Science", "Software Systems"],
    minGPA: 3.1,
    deadline: "Feb 1",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇭🇰",
    name: "University of Hong Kong",
    country: "Hong Kong",
    programs: ["Business Administration", "Computing"],
    minGPA: 3.3,
    deadline: "Dec 30",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇭🇰",
    name: "HKUST",
    country: "Hong Kong",
    programs: ["Engineering", "Data Science"],
    minGPA: 3.2,
    deadline: "Jan 15",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇨🇳",
    name: "Tsinghua University",
    country: "China",
    programs: ["Computer Science", "Engineering"],
    minGPA: 3.6,
    deadline: "Dec 15",
    language: "English",
    match: 90,
    type: "Study Abroad",
    region: "asia",
  },
  {
    flag: "🇨🇳",
    name: "Peking University",
    country: "China",
    programs: ["Information Technologies", "Law"],
    minGPA: 3.5,
    deadline: "Dec 30",
    language: "English",
    match: 87,
    type: "Study Abroad",
    region: "asia",
  },
  {
    flag: "🇰🇷",
    name: "Seoul National University",
    country: "South Korea",
    programs: ["All programs", "Technology"],
    minGPA: 3.3,
    deadline: "Feb 28",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇰🇷",
    name: "KAIST",
    country: "South Korea",
    programs: ["Software Engineering", "Engineering"],
    minGPA: 3.4,
    deadline: "Jan 20",
    language: "English",
    match: 89,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇩🇰",
    name: "Technical University of Denmark",
    country: "Denmark",
    programs: ["Engineering", "Biotechnology"],
    minGPA: 3.0,
    deadline: "Feb 1",
    language: "English",
    match: 83,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇩🇰",
    name: "University of Copenhagen",
    country: "Denmark",
    programs: ["All programs", "Data Science"],
    minGPA: 3.1,
    deadline: "Mar 15",
    language: "English",
    match: 82,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇮🇪",
    name: "Trinity College Dublin",
    country: "Ireland",
    programs: ["Computer Science", "Law"],
    minGPA: 3.2,
    deadline: "Feb 1",
    language: "English",
    match: 86,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇮🇪",
    name: "University College Dublin",
    country: "Ireland",
    programs: ["Business Administration", "Engineering"],
    minGPA: 3.0,
    deadline: "Mar 1",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇫🇷",
    name: "Sorbonne University",
    country: "France",
    programs: ["All programs"],
    minGPA: 3.2,
    deadline: "Jan 31",
    language: "English",
    match: 81,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇫🇷",
    name: "École Polytechnique",
    country: "France",
    programs: ["Engineering", "Technology"],
    minGPA: 3.5,
    deadline: "Dec 15",
    language: "English",
    match: 88,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇿🇦",
    name: "University of Cape Town",
    country: "South Africa",
    programs: ["Applied Science", "Computing", "Business"],
    minGPA: 3.2,
    deadline: "Oct 31",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇿🇦",
    name: "Stellenbosch University",
    country: "South Africa",
    programs: ["Engineering", "Data Science"],
    minGPA: 3.1,
    deadline: "Nov 15",
    language: "English",
    match: 83,
    type: "Study Abroad",
    region: "africa",
  },
  {
    flag: "🇬🇭",
    name: "University of Ghana",
    country: "Ghana",
    programs: ["Information Technology", "Law"],
    minGPA: 3.0,
    deadline: "Nov 30",
    language: "English",
    match: 80,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇰🇪",
    name: "University of Nairobi",
    country: "Kenya",
    programs: ["Computing", "Engineering"],
    minGPA: 3.0,
    deadline: "Dec 1",
    language: "English",
    match: 79,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "�🇬",
    name: "American University in Cairo",
    country: "Egypt",
    programs: ["Business", "Computer Science"],
    minGPA: 3.2,
    deadline: "Nov 10",
    language: "English",
    match: 84,
    type: "Study Abroad",
    region: "africa",
  },
  {
    flag: "🇿🇦",
    name: "University of Pretoria",
    country: "South Africa",
    programs: ["Engineering", "Medicine"],
    minGPA: 3.3,
    deadline: "Nov 20",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇿🇦",
    name: "University of the Witwatersrand",
    country: "South Africa",
    programs: ["Law", "Engineering"],
    minGPA: 3.2,
    deadline: "Dec 5",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇳🇬",
    name: "University of Lagos",
    country: "Nigeria",
    programs: ["Economics", "Computer Science"],
    minGPA: 3.1,
    deadline: "Dec 12",
    language: "English",
    match: 80,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇬🇭",
    name: "Kwame Nkrumah University of Science and Technology",
    country: "Ghana",
    programs: ["Engineering", "Business"],
    minGPA: 3.1,
    deadline: "Dec 18",
    language: "English",
    match: 79,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇺🇬",
    name: "Makerere University",
    country: "Uganda",
    programs: ["Information Technology", "Public Health"],
    minGPA: 3.0,
    deadline: "Dec 20",
    language: "English",
    match: 78,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇹🇿",
    name: "University of Dar es Salaam",
    country: "Tanzania",
    programs: ["Environmental Science", "Engineering"],
    minGPA: 3.0,
    deadline: "Jan 10",
    language: "English",
    match: 77,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇪🇬",
    name: "Cairo University",
    country: "Egypt",
    programs: ["Law", "Engineering"],
    minGPA: 3.2,
    deadline: "Jan 5",
    language: "English",
    match: 81,
    type: "Study Abroad",
    region: "africa",
  },
  {
    flag: "🇳🇬",
    name: "University of Ibadan",
    country: "Nigeria",
    programs: ["Medicine", "Psychology"],
    minGPA: 3.0,
    deadline: "Jan 7",
    language: "English",
    match: 78,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "🇿🇦",
    name: "University of Johannesburg",
    country: "South Africa",
    programs: ["Business", "Computer Science"],
    minGPA: 3.1,
    deadline: "Jan 12",
    language: "English",
    match: 82,
    type: "Exchange",
    region: "africa",
  },
  {
    flag: "�🇺🇸",
    name: "Georgia Tech",
    country: "United States",
    programs: ["Engineering", "Computer Science"],
    minGPA: 3.5,
    deadline: "Jan 15",
    language: "English",
    match: 92,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "Caltech",
    country: "United States",
    programs: ["Applied Science", "Technology"],
    minGPA: 3.8,
    deadline: "Jan 3",
    language: "English",
    match: 91,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "UC Berkeley",
    country: "United States",
    programs: ["Software Systems", "Data Science"],
    minGPA: 3.6,
    deadline: "Jan 8",
    language: "English",
    match: 93,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "Carnegie Mellon University",
    country: "United States",
    programs: ["Computer Science", "Software Engineering"],
    minGPA: 3.7,
    deadline: "Jan 10",
    language: "English",
    match: 95,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "University of Washington",
    country: "United States",
    programs: ["Computing", "Information Technology"],
    minGPA: 3.3,
    deadline: "Feb 1",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "UT Austin",
    country: "United States",
    programs: ["Computer Science", "Business Administration"],
    minGPA: 3.4,
    deadline: "Feb 1",
    language: "English",
    match: 88,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "Cornell University",
    country: "United States",
    programs: ["All programs", "Engineering"],
    minGPA: 3.5,
    deadline: "Jan 2, 2027",
    language: "English",
    match: 89,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "Columbia University",
    country: "United States",
    programs: ["Law", "International Relations"],
    minGPA: 3.6,
    deadline: "Jan 2, 2027",
    language: "English",
    match: 87,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "UCLA",
    country: "United States",
    programs: ["Engineering", "Business"],
    minGPA: 3.4,
    deadline: "Jan 15",
    language: "English",
    match: 88,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇺🇸",
    name: "UCSD",
    country: "United States",
    programs: ["Biotechnology", "Computer Science"],
    minGPA: 3.2,
    deadline: "Feb 1",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇨🇦",
    name: "University of Waterloo",
    country: "Canada",
    programs: ["Software Engineering", "Computing"],
    minGPA: 3.5,
    deadline: "Jan 15",
    language: "English",
    match: 92,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇨🇦",
    name: "University of Alberta",
    country: "Canada",
    programs: ["Engineering", "Information Technology"],
    minGPA: 3.0,
    deadline: "Mar 1",
    language: "English",
    match: 82,
    type: "Exchange",
    region: "americas",
  },
  {
    flag: "🇨🇦",
    name: "McMaster University",
    country: "Canada",
    programs: ["Applied Science", "Engineering"],
    minGPA: 3.1,
    deadline: "Feb 15",
    language: "English",
    match: 83,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇨🇦",
    name: "Université de Montréal",
    country: "Canada",
    programs: ["All programs", "Computer Science"],
    minGPA: 3.2,
    deadline: "Feb 1",
    language: "English",
    match: 80,
    type: "Study Abroad",
    region: "americas",
  },
  {
    flag: "🇬🇧",
    name: "Imperial College London",
    country: "United Kingdom",
    programs: ["Engineering", "Technology"],
    minGPA: 3.7,
    deadline: "Jan 5",
    language: "English",
    match: 94,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇬🇧",
    name: "UCL",
    country: "United Kingdom",
    programs: ["Computer Science", "Law"],
    minGPA: 3.5,
    deadline: "Jan 15",
    language: "English",
    match: 89,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇬🇧",
    name: "University of Edinburgh",
    country: "United Kingdom",
    programs: ["Data Science", "All programs"],
    minGPA: 3.3,
    deadline: "Feb 1",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇬🇧",
    name: "King's College London",
    country: "United Kingdom",
    programs: ["International Relations", "Business"],
    minGPA: 3.3,
    deadline: "Feb 15",
    language: "English",
    match: 85,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇬🇧",
    name: "University of Manchester",
    country: "United Kingdom",
    programs: ["Engineering", "Computing"],
    minGPA: 3.2,
    deadline: "Feb 20",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇬🇧",
    name: "University of Warwick",
    country: "United Kingdom",
    programs: ["Business Administration", "Software Systems"],
    minGPA: 3.3,
    deadline: "Mar 1",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇩🇪",
    name: "RWTH Aachen University",
    country: "Germany",
    programs: ["Engineering", "Technology"],
    minGPA: 3.1,
    deadline: "Mar 1",
    language: "English",
    match: 87,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇩🇪",
    name: "Heidelberg University",
    country: "Germany",
    programs: ["Biotechnology", "All programs"],
    minGPA: 3.3,
    deadline: "Jan 15",
    language: "English",
    match: 82,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇩🇪",
    name: "Technical University of Berlin",
    country: "Germany",
    programs: ["Computer Science", "Engineering"],
    minGPA: 3.0,
    deadline: "Apr 1",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇩🇪",
    name: "Karlsruhe Institute of Tech",
    country: "Germany",
    programs: ["Technology", "Software Engineering"],
    minGPA: 3.1,
    deadline: "Mar 15",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇫🇷",
    name: "CentraleSupélec",
    country: "France",
    programs: ["Engineering", "Technology"],
    minGPA: 3.4,
    deadline: "Feb 15",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇳🇱",
    name: "Leiden University",
    country: "Netherlands",
    programs: ["Law", "Political Science"],
    minGPA: 3.1,
    deadline: "Mar 1",
    language: "English",
    match: 81,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇳🇱",
    name: "Utrecht University",
    country: "Netherlands",
    programs: ["All programs", "Data Science"],
    minGPA: 3.2,
    deadline: "Feb 15",
    language: "English",
    match: 83,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇳🇱",
    name: "Groningen University",
    country: "Netherlands",
    programs: ["Business", "Computing"],
    minGPA: 3.0,
    deadline: "Apr 1",
    language: "English",
    match: 82,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇸🇪",
    name: "Lund University",
    country: "Sweden",
    programs: ["All programs", "Engineering"],
    minGPA: 3.1,
    deadline: "Jan 15",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇸🇪",
    name: "Uppsala University",
    country: "Sweden",
    programs: ["Information Technology", "Biotechnology"],
    minGPA: 3.0,
    deadline: "Jan 15",
    language: "English",
    match: 83,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇧🇪",
    name: "Ghent University",
    country: "Belgium",
    programs: ["Engineering", "Applied Science"],
    minGPA: 3.0,
    deadline: "Mar 1",
    language: "English",
    match: 81,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇨🇭",
    name: "University of Zurich",
    country: "Switzerland",
    programs: ["Business Administration", "Data Science"],
    minGPA: 3.3,
    deadline: "Jan 30",
    language: "English",
    match: 85,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇮🇹",
    name: "Politecnico di Milano",
    country: "Italy",
    programs: ["Engineering", "Technology"],
    minGPA: 3.2,
    deadline: "Feb 28",
    language: "English",
    match: 88,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇮🇹",
    name: "University of Bologna",
    country: "Italy",
    programs: ["All programs", "Law"],
    minGPA: 3.0,
    deadline: "Mar 30",
    language: "English",
    match: 80,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇪🇸",
    name: "Universitat de Barcelona",
    country: "Spain",
    programs: ["Business", "All programs"],
    minGPA: 2.9,
    deadline: "Apr 15",
    language: "English",
    match: 78,
    type: "Study Abroad",
    region: "europe",
  },
  {
    flag: "🇪🇸",
    name: "Universidad Autónoma de Madrid",
    country: "Spain",
    programs: ["Computer Science", "International Relations"],
    minGPA: 3.0,
    deadline: "Mar 15",
    language: "English",
    match: 79,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇫🇮",
    name: "Aalto University",
    country: "Finland",
    programs: ["Technology", "Computer Science", "Business"],
    minGPA: 3.2,
    deadline: "Jan 31",
    language: "English",
    match: 88,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇳🇴",
    name: "University of Oslo",
    country: "Norway",
    programs: ["Data Science", "All programs"],
    minGPA: 3.1,
    deadline: "Feb 15",
    language: "English",
    match: 82,
    type: "Exchange",
    region: "europe",
  },
  {
    flag: "🇦🇺",
    name: "University of Sydney",
    country: "Australia",
    programs: ["All programs", "Software Engineering"],
    minGPA: 3.3,
    deadline: "Apr 30",
    language: "English",
    match: 87,
    type: "Study Abroad",
    region: "asia",
  },
  {
    flag: "🇦🇺",
    name: "UNSW Sydney",
    country: "Australia",
    programs: ["Engineering", "Computing"],
    minGPA: 3.2,
    deadline: "May 15",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇦🇺",
    name: "University of Queensland",
    country: "Australia",
    programs: ["Biotechnology", "Information Technology"],
    minGPA: 3.1,
    deadline: "Apr 1",
    language: "English",
    match: 83,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇳🇿",
    name: "University of Auckland",
    country: "New Zealand",
    programs: ["Engineering", "All programs"],
    minGPA: 3.0,
    deadline: "Mar 15",
    language: "English",
    match: 81,
    type: "Study Abroad",
    region: "asia",
  },
  {
    flag: "🇨🇳",
    name: "Fudan University",
    country: "China",
    programs: ["Business Administration", "Software Systems"],
    minGPA: 3.4,
    deadline: "Feb 25",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇨🇳",
    name: "Shanghai Jiao Tong University",
    country: "China",
    programs: ["Engineering", "Technology"],
    minGPA: 3.3,
    deadline: "Jan 20",
    language: "English",
    match: 84,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇯🇵",
    name: "Tokyo Institute of Technology",
    country: "Japan",
    programs: ["Technology", "Engineering"],
    minGPA: 3.4,
    deadline: "Dec 10",
    language: "English",
    match: 86,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇯🇵",
    name: "Osaka University",
    country: "Japan",
    programs: ["Applied Science", "Computing"],
    minGPA: 3.2,
    deadline: "Jan 15",
    language: "English",
    match: 81,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇰🇷",
    name: "Yonsei University",
    country: "South Korea",
    programs: ["Business", "All programs"],
    minGPA: 3.1,
    deadline: "Feb 28",
    language: "English",
    match: 83,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇰🇷",
    name: "Korea University",
    country: "South Korea",
    programs: ["Law", "Information Technologies"],
    minGPA: 3.2,
    deadline: "Feb 15",
    language: "English",
    match: 84,
    type: "Study Abroad",
    region: "asia",
  },
  {
    flag: "🇹🇼",
    name: "National Taiwan University",
    country: "Taiwan",
    programs: ["Engineering", "Technology", "Computer Science"],
    minGPA: 3.2,
    deadline: "Jan 30",
    language: "English",
    match: 85,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇮🇳",
    name: "IIT Bombay",
    country: "India",
    programs: ["Engineering", "Computer Science", "Data Science"],
    minGPA: 3.5,
    deadline: "Jan 15",
    language: "English",
    match: 89,
    type: "Exchange",
    region: "asia",
  },
  {
    flag: "🇮🇳",
    name: "IIT Delhi",
    country: "India",
    programs: ["Technology", "Software Engineering"],
    minGPA: 3.4,
    deadline: "Jan 30",
    language: "English",
    match: 87,
    type: "Exchange",
    region: "asia",
  }
]

async function runSeed() {
  try {
    await mongoose.connect(mongoDBURL)
    console.log('Connected to MongoDB for seeding')

    await University.deleteMany({})
    console.log('Cleared existing universities')

    await University.insertMany(universities)
    console.log(`Inserted ${universities.length} universities`)

    await mongoose.disconnect()
    console.log('Disconnected after seeding')
  } catch (err) {
    console.error('Seeding error:', err)
    process.exit(1)
  }
}

runSeed()
